# -*- coding: utf-8 -*-
"""Copy of PP WEEK-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A-_2aRj6Ln3U19qLBwX148_KYBPFw-Y-

Write a program to calculate compound interest when principal, rate and number of
periods are given.
"""

principal_amount=int(input("Enter principal amount"))
rate = int(input("Enter rate of interest"))
num_of_periods=int(input("Enter number of periods"))
time = int(input("Enter time"))
compound_interest=principal_amount*(1+rate/num_of_periods)**(num_of_periods*time)-principal_amount
print(compound_interest)

"""Given coordinates (x1, y1), (x2, y2) find the distance between two points."""

x1,y1=int(input("Enter x1 : ")),int(input("Enter y1 : "))
x2,y2=int(input("Enter x2 : ")),int(input("Enter y2 : "))
distance=((x1-x2)**2+(y1-y2)**2)**0.5
print(distance)

"""Read name, address, email and phone number of a person through keyboard and print the
details.
"""

name=input("Enter name : ")
email=input("Enter email id : ")
phn_num=int(input("Enter phone number : "))
print(name,email,phn_num)